#!/bin/sh

if [ $(echo "(+ 2 3)" | ./scheme) -ne 5 ]; then
    echo "test 1 not passed!!";
    exit -1;
else
    echo "test 1 passed!!";
fi

if [ $(echo "(- 2 3)" | ./scheme) -ne -1 ]; then
    echo "test 2 not passed!!";
    exit -1;
else
    echo "test 2 passed!!";
fi


if [ $(echo "(* 2 3)" | ./scheme) -ne 6 ]; then
    echo "test 3 not passed!!";
    exit -1;
else
    echo "test 3 passed!!";
fi

if [ $(echo "(/ 15 3)" | ./scheme) -ne 5 ]; then
    echo "test 4 not passed!!";
    exit -1;
else
    echo "test 4 passed!!";
fi


if [ $(echo "(+ (- 4 1) 3)" | ./scheme) -ne 6 ]; then
    echo "test 5 not passed!!";
    exit;
else
    echo "test 5 passed!!";
fi

if [ "$(echo '(cons 1 3)' | ./scheme)" != '( 1 . 3 )'  ]; then
    echo "test 6 not passed!!";
    exit -1;
else
    echo "test 6 passed!!";
fi

if [ $(echo "(car (cons 1 3))" | ./scheme) -ne 1 ]; then
    echo "test 7 not passed!!";
    exit -1;
else
    echo "test 7 passed!!";
fi

if [ $(echo "(cdr (cons 1 3))" | ./scheme) -ne 3 ]; then
    echo "test 8 not passed!!";
    exit -1;
else
    echo "test 8 passed!!";
fi

if [ "$(echo '(define s (lambda (x) (+ x 1 ))) (s 1)' | ./scheme)" != 'LAMBDA
2' ]; then
    echo "test 9 not passed!!";
    exit -1;
else
    echo "test 9 passed!!";
fi

if [ "$(echo '(= 3.0 3)' | ./scheme)" != "#t" ]; then
    echo "test 10 not passed!!";
    exit -1;
else
    echo "test 10 passed!!";
fi

if [ $(echo "(if 3 4 5)" | ./scheme) -ne 4 ]; then
    echo "test 11 not passed!!";
    exit -1;
else
    echo "test 11 passed!!";
fi

if [ $(echo '(if #f 4 5)' | ./scheme) -ne 5 ]; then
    echo "test 12 not passed!!";
    exit -1;
else
    echo "test 12 passed!!";
fi

echo "all tests passed successfully!!"
